### ISSUE TITLE
NCover Console: Paths containing spaces

### ISSUE THREAD

**Issue by seanbiefeld** [mxriverlynn/Albacore#49] opened 2010-01-22 06:25 UTC
the ncover console task cannot handle paths with spaces in the them when pointing to assemblies, if it finds a space it replaces it with " "
ncoverconsole.rb line 42:
result = run_command "NCover.Console", command_parameters.join(" ")

**Comment by mxriverlynn** [comment] 2010-02-09 18:31
I'm unable to reproduce the issue. can you provide your rake task configuration?

**Comment by mxriverlynn** [comment] 2010-02-17 21:55
i finally reproduced this. will be fixed in next release.

**Comment by mxriverlynn** [comment] 2010-02-18 03:45
fixed and release in v0.1.2

**Closed as completed by mxriverlynn** 2010-02-18 03:45 UTC
Labels: Stuff To Fix
