### ISSUE TITLE
NUnit options in Albacore.configure doesn't work

### ISSUE THREAD

**Issue by carlhoerberg** [mxriverlynn/Albacore#123] opened 2010-12-15 09:32 UTC
```
require 'rubygems'
require 'albacore'

Albacore.configure do |c|
  c.nunit do |nunit|
    nunit.command = 'packages/NUnit.2.5.7.10213/Tools/nunit-console.exe'
    nunit.options '/noshadow'
  end
end

nunit do |nunit|
  nunit.assemblies = 'mytests.dll'
end
```

results in 

```
rake aborted!
undefined method `options' for #<OpenStruct command="packages/NUnit.2.5.7.10213/Tools/nunit-console.exe">
```

**Comment by mxriverlynn** [comment] 2010-12-15 12:03
this is caused by another issue that i've been trying to fix for a while - fortunately it's an easy work around. set the .options with an = 

<pre><code>nunit.options = "/noshadow"</code></pre> 


and it should work.

the nunit object was built differently the rest of albacore, and i didn't have time to rebuild it for the most recent releases. i'll get this fixed eventually, though.

**Comment by carlhoerberg** [comment] 2010-12-15 13:09
i've tried that too, but that ends up with: 
    undefined method `join' for "/noshadow":String

albacore 0.2.2
ruby 1.8.7 (2008-08-11 patchlevel 72) [i386-cygwin]

but 
    nunit.options = ['/noshadow']

works fine

**Comment by mxriverlynn** [comment] 2010-12-15 14:39
ah, thanks for the correction.

**Comment by haf** [comment] 2012-01-30 06:55
Is this issue done?

**Comment by haf** [comment] 2012-01-31 12:25
Duplicate #73?

**Comment by mxriverlynn** [comment] 2012-01-31 19:04
yeah, this is a dup of #73, when it comes down to it. closing this one in favor of fixing #73

**Closed as completed by mxriverlynn** 2012-01-31 19:04 UTC
