### ISSUE TITLE
Allow .Net Version to be a parameter or look for MSBuild in the path

### ISSUE THREAD

**Issue by MarkBorcherding** [mxriverlynn/Albacore#67] opened 2010-05-11 12:29 UTC
We are trying to use the .Net 4.0 compiler, but the MSBuild task is hard coded for v3.5. 

```
File.join(win_dir.dup, 'Microsoft.NET', 'Framework', 'v3.5', 'MSBuild.exe')
```

Previously we were doing:

```
sh 'msbuild my.sln'
```

This worked because we have the right MSBuild in our path, but switching to the MSBuild task fails.

**Comment by mxriverlynn** [comment] 2010-05-11 13:42
Hi mark,

the cause of this is an option called "require_valid_command" that i stuck in the framework way back in the early versions. it's caused me a lot of problems and I plan on getting rid of it in the next release. 

while we're working on a better fix for this for the next major release (v0.2), you have a couple of options to get around it right now:

1) set the path_to_command to point to your MSBuild location

<pre><code>msbuild :build do |msb|
  msb.path_to_command = "./some/folder/somewhere/msbuild.exe"
  #... other settings here
</code></pre>


or 2) set the .require_valid_command attribute to false:

<pre><code>msbuild :build do |msb|
  msb.require_valid_command = false
  #... other options here
</code></pre>


the permanent fix is going to be partially completed by ticket #67 and probably a few others that haven't been written up yet. i hope this workaround gets you what you need for now, though.

**Comment by MarkBorcherding** [comment] 2010-05-11 13:48
Thanks! stevenharman already hooked me up with:
    msbuild :doit do |msb|
     msb.path_to_command File.join(ENV['WINDIR'], 'Microsoft.NET', 'Framework', 'v4.0.30319', 'MSBuild.exe')
     ... #other config here
    end

....which will work for me for now. I knew it was probably under works, but didn't see it mentioned in the issues list at all.

**Comment by mxriverlynn** [comment] 2010-05-11 13:57
cool. glad it's working for you. we'll get this fixed up properly soon. :)

**Closed as completed by mxriverlynn** 2010-05-11 13:57 UTC
